In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x1)

[5 0 3 3 7 9]


In [2]:
# version check
np.__version__

'2.0.1'

In [3]:
#HOW TO KNOW ABOUT A FUNCTION, DETAILS SHOW UP
np.zeros?


Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [93]:
#similarly 
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [5]:
#first and last values are starting an ending points respevtively and the first one is inclusie while the last is exclusive
arr = np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [6]:
#3rd parameter is steps
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
#3rd parameter is steps
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [8]:
arr = np.arange(-100,100)
print(arr)

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81  -80  -79  -78  -77  -76  -75  -74  -73
  -72  -71  -70  -69  -68  -67  -66  -65  -64  -63  -62  -61  -60  -59
  -58  -57  -56  -55  -54  -53  -52  -51  -50  -49  -48  -47  -46  -45
  -44  -43  -42  -41  -40  -39  -38  -37  -36  -35  -34  -33  -32  -31
  -30  -29  -28  -27  -26  -25  -24  -23  -22  -21  -20  -19  -18  -17
  -16  -15  -14  -13  -12  -11  -10   -9   -8   -7   -6   -5   -4   -3
   -2   -1    0    1    2    3    4    5    6    7    8    9   10   11
   12   13   14   15   16   17   18   19   20   21   22   23   24   25
   26   27   28   29   30   31   32   33   34   35   36   37   38   39
   40   41   42   43   44   45   46   47   48   49   50   51   52   53
   54   55   56   57   58   59   60   61   62   63   64   65   66   67
   68   69   70   71   72   73   74   75   76   77   78   79   80   81
   82   83   84   85   86   87   88   89   90   91   92   93   94   95
   96 

In [9]:
#shaping
np.arange(0,9,).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.array({0,1,2,3,4,56,5,5})

array({0, 1, 2, 3, 4, 5, 56}, dtype=object)

In [11]:
range(0,10)

range(0, 10)

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
Difference between list and dictionary and numpy
# list is a collection of items that can be of any data type
# dictionary is a collection of key-value pairs
# numpy is a library for efficient numerical computation
# numpy arrays are similar to lists but are more memory efficient and faster for numerical computations


In [23]:
l2 = [x for x in range(0,10)]
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
a = [ str(x) for x in range(0,10)]
a

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [24]:
l3 = [x**2 for x in range(0,10)]
l3


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [25]:
import array 

In [62]:
arr = array.array('i',l3)
print(arr)
type(arr)

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])


array.array

In [49]:
arr1 = array.array('i', [x**2 for x in range(0,13)])
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144])

In [60]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.array(x+3 for x in range(0,10))
print(array)

<module 'array' (built-in)>


In [64]:
arrr = array.array('f',l3)
arrr

array('f', [0.0, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0])

In [65]:
l2d = [[1,2,23,3,3],[1,2,3,4,4,3,2]]
l2d

[[1, 2, 23, 3, 3], [1, 2, 3, 4, 4, 3, 2]]

In [38]:
lc2d = [range(i,i+3) for i in range(0,3)]
np.array(lc2d)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [94]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
np.zeros([10,10], dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [97]:
np.zeros([3,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [4]:
import numpy as np

In [1]:
ary = np.array([1]*10)
ary1 = np.array([1,0,0,0,0,0,0,0,0,1 ])

print(ary)
for x in range():
    
    print(ary1)
print(ary)

NameError: name 'np' is not defined

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [40]:
nmsq = [range(i,i+3) for i in range(0,3)]
np.array(nmsq)
print(nmsq)

[range(0, 3), range(1, 4), range(2, 5)]


In [45]:
ar = np.arange(0,9, dtype = 'float').reshape(3,3)
ar[:] = 3.14
ar

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [46]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [57]:
#identity matrix 
waee = np.eye(5,5, dtype = int)
waee

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [58]:
np.transpose(waee)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [3]:
import numpy as np

In [8]:
a = np.full(3,5)
b = np.full(3,5)
a+b


array([10, 10, 10])