Assignment 1

In [5]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [19]:
np.arange(0,9,).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.random.randint(5,10)

8

In [3]:
np.random.standard_normal(25)

array([ 0.33295708, -0.56271133,  0.22932106, -0.69090998,  0.5810344 ,
        1.23283061, -0.11714223, -0.34513755,  0.14643483, -0.30477059,
        1.86782705, -1.85550593,  0.87285143, -1.37894683,  0.99250461,
       -0.15606116,  1.97910863,  2.00457514,  0.06611834,  0.39301479,
        1.85376404,  0.39128932,  0.75536157,  1.23700303,  2.12775199])

In [50]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [51]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [4]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
arr[3:4,4]

array([20])

In [139]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [153]:
arr[4:]

array([[21, 22, 23, 24, 25]])

In [20]:
np.sum(arr,axis=0)

array([55, 60, 65, 70, 75])

In [164]:

np.max(arr, axis=0)

array([21, 22, 23, 24, 25])

In [166]:
np.min(arr, axis=0)

array([1, 2, 3, 4, 5])

In [165]:
np.std(arr, axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [167]:
np.var(arr,axis=0)

array([50., 50., 50., 50., 50.])

In [10]:
a = np.full((6,6),np.nan)
a[1:5,1:5]=1
a

array([[nan, nan, nan, nan, nan, nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan,  1.,  1.,  1.,  1., nan],
       [nan, nan, nan, nan, nan, nan]])

Assingment 2

In [190]:
arr1d = np.random.rand(5)
print(arr1d)
arr2d = np.random.randint(1,10,4).reshape(2,2)
print(arr2d)
arr3d = np.random.randint(1,10,9).reshape(3,3)
print(arr3d)


[0.45772691 0.54362775 0.22585093 0.98455673 0.20319545]
[[8 8]
 [6 2]]
[[2 4 4]
 [6 1 8]
 [7 5 3]]


In [191]:
print(arr1d.dtype)
print(arr2d.dtype)
print(arr3d.dtype)

print(arr1d.shape)
print(arr2d.shape)
print(arr3d.shape)

float64
int32
int32
(5,)
(2, 2)
(3, 3)


In [193]:
asd = np.zeros(12)
asd

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [195]:
ard = np.ones(4, dtype=int).reshape(2,2)
ard

array([[1, 1],
       [1, 1]])

In [227]:
maths = np.random.randint(0,100,20)
maths

array([93, 71, 89,  2, 23, 12,  7, 32, 90, 67, 35, 13, 90, 95, 17, 93, 80,
       26, 75,  0], dtype=int32)

In [229]:
math2 = maths.copy()
print(math2)

[93 71 89  2 23 12  7 32 90 67 35 13 90 95 17 93 80 26 75  0]


In [22]:
a = np.eye(5, dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
a.reshape(-1)

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1])

In [37]:
ghd = np.random.randint(0,10,9).reshape(3,3)
ghd

array([[3, 0, 9],
       [1, 9, 4],
       [3, 4, 8]], dtype=int32)

In [38]:
new_row = [12,18,11]
np.append(ghd,[new_row], axis = 0)

array([[ 3,  0,  9],
       [ 1,  9,  4],
       [ 3,  4,  8],
       [12, 18, 11]])

In [259]:
np.vsplit(ghd,1)

[array([[8, 5, 0],
        [7, 4, 2],
        [8, 6, 4]], dtype=int32)]

In [257]:
np.hsplit(ghd,1)

[array([[8, 5, 0],
        [7, 4, 2],
        [8, 6, 4]], dtype=int32)]

In [40]:
arr4d = np.random.randn(16).reshape(4,4)
arr4d

array([[-1.32849561, -0.28656487, -0.20086265, -0.27681045],
       [-1.10692174,  1.04308814,  0.20051823,  0.52747919],
       [-0.18126293,  1.37548858, -1.17741593,  0.19054331],
       [ 2.32027805,  0.94068727,  0.26379169,  0.44084869]])

In [42]:
newd = [1,2,3,4]
print(newd)

np.append(arr4d, [newd], axis = 0 )

[1, 2, 3, 4]


array([[-1.32849561, -0.28656487, -0.20086265, -0.27681045],
       [-1.10692174,  1.04308814,  0.20051823,  0.52747919],
       [-0.18126293,  1.37548858, -1.17741593,  0.19054331],
       [ 2.32027805,  0.94068727,  0.26379169,  0.44084869],
       [ 1.        ,  2.        ,  3.        ,  4.        ]])

In [274]:
sdf =np.random.random(5)
sdf

array([0.28530534, 0.00121457, 0.59359497, 0.16010592, 0.03116252])

In [14]:
np.eye(4,4)+4


array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [44]:
ar302 = np.array([1.2,6.5,8.0,7.7,3.4,1.9])
np.ceil(ar302)

array([2., 7., 8., 8., 4., 2.])

In [45]:
np.floor(ar302)

array([1., 6., 8., 7., 3., 1.])

In [46]:
np.round(ar302)

array([1., 6., 8., 8., 3., 2.])

In [16]:
ar303 = np.arange(3,28).reshape(5,5)
ar303


array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27]])

In [17]:
np.min(ar303,axis=1)


array([ 3,  8, 13, 18, 23])

In [50]:
np.max(ar303,axis=0)


array([23, 24, 25, 26, 27])

In [51]:
np.var(ar303,axis=0)


array([50., 50., 50., 50., 50.])

In [52]:
np.std(ar303,axis=0)


array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [53]:
nv = np.full(10,np.nan)
nv[6]=200
nv

array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [54]:
vec1 = np.arange(100,151)
vec1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [55]:
vec1[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [56]:
np.arange(0,25).reshape(5,5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
ar403 = np.array([1,0,2,0,0,4,0,8])
np.nonzero(ar403)[0]

array([0, 2, 5, 7])

In [58]:
ardff = np.full(100,1).reshape(10,10)
ardff[1:9,1:9]=0
ardff


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [20]:
ard1 = np.ones((9,9))
ard1[::2,::2]=1
ard1[1::,1::2]=0
ard1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [66]:
np.random.seed(12)
ard2 = np.random.randint(0,9,9).reshape(3,3)
ard2

array([[6, 1, 2],
       [3, 3, 0],
       [6, 1, 4]], dtype=int32)

In [65]:
np.random.seed(5)
ard2 = np.random.randint(20,50,9).reshape(3,3)
ard2

array([[23, 34, 35],
       [49, 26, 42],
       [36, 29, 28]], dtype=int32)

In [67]:
np.sum((ard1,ard2),axis=0)

array([[29, 35, 37],
       [52, 29, 42],
       [42, 30, 32]])

In [68]:
np.multiply(ard1,ard2)

array([[138,  34,  70],
       [147,  78,   0],
       [216,  29, 112]], dtype=int32)

In [69]:
np.subtract(ard1,ard2)

array([[17, 33, 33],
       [46, 23, 42],
       [30, 28, 24]], dtype=int32)