In [12]:
#squarinf a number
a = 7
print(a**4)


2401


In [13]:
#spiltting 
s = "hi there sam!"
list1 = s.split()
print(list1)
print(s.split())

email = "acsec@sdcds.csd"
print(email.split("@"))


['hi', 'there', 'sam!']
['hi', 'there', 'sam!']


In [14]:
#Indexing
planet = "earth"
diameter = 12742
print("the diameter of {0} is earth {1} km" .format(planet, diameter))


the diameter of earth is earth 12742 km


In [1]:
#List
lst = [1,2,[3,4], [5,[100,200,['hello']],23,11],1,7]
grab = lst[3][1][2][0]
print(grab)

hello


In [3]:
#Dictionary
d = {'k1':[1,2,3,{'tricky': ['oh', 'man', 'inception', {'target' : [1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


In [4]:
#. Write a program to input roll no, student name, marks of physics, chemistry and maths out of 100. (0-100).Calculate total,
#  percentage, calculate STATUS (pass, fail) if students scores above 40 in all the 3 subjects the STATUS should be pass otherwise
#  fail. Calculate GRADE if STATUS is pass.

Roll_no = int(input("Roll no : "))
student_name = input("name : ")
Marks_Of_Physics = int(input("Marks Of Physics : "))
Marks_Of_Chemistry = int(input("Marks Of Chemistry : "))
Marks_Of_Maths = int(input("Marks Of Maths : "))

print("Roll No. : ", Roll_no)
print("Student Name : ", student_name)
print("Marks in Physics : ", Marks_Of_Physics)
print("Marks in Chemistry : ", Marks_Of_Chemistry)
print("Marks in Maths : ", Marks_Of_Maths)


total = Marks_Of_Physics + Marks_Of_Chemistry + Marks_Of_Maths
percentage = total / 3

def grade():
    if(total>70 ):
        print("Grade : Distinction")
    elif(total<40):
        print("Grade : Fail")
    elif(total>60):
        print("Grade : First Class")
    elif(total>50):
        print("Grade : Second Class")
    elif(total>40):
        print("Grade : Pass")
grade()

if(Marks_Of_Chemistry >40) and (Marks_Of_Physics>40)  and (Marks_Of_Maths>40):
    print("Status: Pass")
else :
    print("Fail")


Roll No. :  12
Student Name :  abhishek
Marks in Physics :  98
Marks in Chemistry :  99
Marks in Maths :  100
Grade : Distinction
Status: Pass


In [ ]:
email = input("Enter Email : ")
name = input("Name : ")
Basic_salary = int(input("Salary : "))
experience = int(input("Years of experince : "))
hra = Basic_salary*.035
da = Basic_salary*.58
pf = Basic_salary*0.095
a = 0

print("Name : ", name)
print("Email : ", email)
print("Basic Salary : ", Basic_salary)
print("HRA : ", hra)
print("DA : ", da)
print("PF : ", pf)

if (experience >= 30):
    a = 0.59
    print("Bonus : ", Basic_salary+(Basic_salary*a))
elif (experience>= 23):
    a = 0.51
    print("Bonus : ", Basic_salary+(Basic_salary*a))
elif (experience>= 15):
    a = 0.45
    print("Bonus : ", Basic_salary+(Basic_salary*a))
elif (experience >= 7):
    a = 0.33
    print("Bonus : ", Basic_salary+(Basic_salary*a))
elif (experience<7):
    a = 0.16
    print("Bonus : ", Basic_salary+(Basic_salary*a))



In [8]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x1)

[5 0 3 3 7 9]


In [14]:
# version check
np.__version__

In [15]:
#HOW TO KNOW ABOUT A FUNCTION, DETAILS SHOW UP
np.zeros?


Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [ ]:
#similarly 
help(np.zeroes)

In [22]:
#first and last values are starting an ending points respevtively and the first one is inclusie while the last is exclusive
arr = np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [23]:
#3rd parameter is steps
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [24]:
#3rd parameter is steps
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [26]:
arr = np.arange(-100,100)
print(arr)

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81  -80  -79  -78  -77  -76  -75  -74  -73
  -72  -71  -70  -69  -68  -67  -66  -65  -64  -63  -62  -61  -60  -59
  -58  -57  -56  -55  -54  -53  -52  -51  -50  -49  -48  -47  -46  -45
  -44  -43  -42  -41  -40  -39  -38  -37  -36  -35  -34  -33  -32  -31
  -30  -29  -28  -27  -26  -25  -24  -23  -22  -21  -20  -19  -18  -17
  -16  -15  -14  -13  -12  -11  -10   -9   -8   -7   -6   -5   -4   -3
   -2   -1    0    1    2    3    4    5    6    7    8    9   10   11
   12   13   14   15   16   17   18   19   20   21   22   23   24   25
   26   27   28   29   30   31   32   33   34   35   36   37   38   39
   40   41   42   43   44   45   46   47   48   49   50   51   52   53
   54   55   56   57   58   59   60   61   62   63   64   65   66   67
   68   69   70   71   72   73   74   75   76   77   78   79   80   81
   82   83   84   85   86   87   88   89   90   91   92   93   94   95
   96 

In [30]:
#shaping
np.arange(0,9,).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np.array({0,1,2,3,4,56,5,5})

array({0, 1, 2, 3, 4, 5, 56}, dtype=object)